### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by Xiaowei-coder** [LMSAudio/Complex_PF#1]
there is a error:  No such file or directory: './results/sigStruct_5.mat'. Could you please give me some advice? thanks!!!!!

**Comment by ModarHalimeh** [comment]
Hi. You are probably trying to write your results into the folder ./results which does not exist. Try creating an empty folder ./results for the network to save the results in.

**Comment by Xiaowei-coder** [comment]
Hi, friend. Thanks for your kind reply!! I have soveld the problem by your method.

**Comment by ModarHalimeh** [comment]
You are welcome! Glad I could help.
